### ISSUE TITLE
openssl: CVE-2015-3193, CVE-2015-3194, CVE-2015-3195, CVE-2015-3196

### ISSUE THREAD

**Issue by tianon** [docker-library/official-images#1235]
CVE-2015-3193, CVE-2015-3194, CVE-2015-3195, CVE-2015-3196, *CVE-2015-1794*

https://mta.openssl.org/pipermail/openssl-announce/2015-December/000050.html
https://mta.openssl.org/pipermail/openssl-announce/2015-December/000055.html

- [x] `alpine`: https://github.com/docker-library/official-images/pull/1255 -- `libssl1.0-1.0.2d-r0`
  - http://bugs.alpinelinux.org/issues/4921
  - http://git.alpinelinux.org/cgit/aports/log/main/openssl
  - http://bugs.alpinelinux.org/projects/alpine/search?q=CVE-2015-3193
  - http://bugs.alpinelinux.org/projects/alpine/search?q=CVE-2015-3194
  - http://bugs.alpinelinux.org/projects/alpine/search?q=CVE-2015-3195
  - http://bugs.alpinelinux.org/projects/alpine/search?q=CVE-2015-3196
  - http://bugs.alpinelinux.org/projects/alpine/search?q=CVE-2015-1794
- [x] `busybox`: *not affected*
- [x] `centos` (RHEL derivative): https://github.com/docker-library/official-images/pull/1275 -- `openssl-libs-1.0.1e-42.el7.9.x86_64`
  - https://access.redhat.com/security/cve/CVE-2015-3193
  - https://access.redhat.com/security/cve/CVE-2015-3194
  - https://access.redhat.com/security/cve/CVE-2015-3195
  - https://access.redhat.com/security/cve/CVE-2015-3196
  - https://access.redhat.com/security/cve/CVE-2015-1794
- [ ] `crux`: `OpenSSL 1.0.2d` -- **update available**
  - https://crux.nu/gitweb/?p=ports/core.git;a=history;f=openssl;hb=HEAD
- [x] `debian`: https://github.com/docker-library/official-images/pull/1241 -- no SSL in the base image, but many descendants
  - https://security-tracker.debian.org/tracker/CVE-2015-3193
  - https://security-tracker.debian.org/tracker/CVE-2015-3194
  - https://security-tracker.debian.org/tracker/CVE-2015-3195
  - https://security-tracker.debian.org/tracker/CVE-2015-3196
  - https://security-tracker.debian.org/tracker/CVE-2015-1794
- [x] `fedora`: https://github.com/docker-library/official-images/pull/1316 -- `openssl-libs-1.0.2d-3.fc23.x86_64`
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2015-3193
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2015-3194
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2015-3195
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2015-3196
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2015-1794
- [x] `mageia`: https://github.com/docker-library/official-images/pull/1254 -- `lib64openssl1.0.0-1.0.2d-1.mga5`
  - https://bugs.mageia.org/show_bug.cgi?id=17292
  - https://bugs.mageia.org/buglist.cgi?quicksearch=ALL%20CVE-2015-3193
  - https://bugs.mageia.org/buglist.cgi?quicksearch=ALL%20CVE-2015-3194
  - https://bugs.mageia.org/buglist.cgi?quicksearch=ALL%20CVE-2015-3195
  - https://bugs.mageia.org/buglist.cgi?quicksearch=ALL%20CVE-2015-3196
  - https://bugs.mageia.org/buglist.cgi?quicksearch=ALL%20CVE-2015-1794
- [x] `opensuse`: https://github.com/docker-library/official-images/pull/1257 -- `openssl-1.0.1i-4.1.x86_64`/`libopenssl1_0_0-1.0.1i-4.1.x86_64`
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2015-3193
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2015-3194
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2015-3195
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2015-3196
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2015-1794
- [x] `oraclelinux`: https://github.com/docker-library/official-images/pull/1287 -- `openssl-libs-1.0.1e-42.el7_1.9.x86_64`
  - http://linux.oracle.com/cve/CVE-2015-3193.html
  - http://linux.oracle.com/cve/CVE-2015-3194.html
  - http://linux.oracle.com/cve/CVE-2015-3195.html
  - http://linux.oracle.com/cve/CVE-2015-3196.html
  - http://linux.oracle.com/cve/CVE-2015-1794.html
- [ ] `sourcemage`: `OpenSSL 0.9.8zd` -- **update available**
  - http://www.sourcemage.org/projects/grimoire/repository/changes/crypto/openssl?rev=master
  - http://www.sourcemage.org/projects/grimoire/search?scope=all&q=CVE-2015-3193
  - http://www.sourcemage.org/projects/grimoire/search?scope=all&q=CVE-2015-3194
  - http://www.sourcemage.org/projects/grimoire/search?scope=all&q=CVE-2015-3195
  - http://www.sourcemage.org/projects/grimoire/search?scope=all&q=CVE-2015-3196
  - http://www.sourcemage.org/projects/grimoire/search?scope=all&q=CVE-2015-1794
- [x] `ubuntu`: https://github.com/docker-library/official-images/pull/1251 -- `libssl1.0.0_1.0.1f-1ubuntu2.15`
  - http://people.canonical.com/~ubuntu-security/cve/2015/CVE-2015-3193.html
  - http://people.canonical.com/~ubuntu-security/cve/2015/CVE-2015-3194.html
  - http://people.canonical.com/~ubuntu-security/cve/2015/CVE-2015-3195.html
  - http://people.canonical.com/~ubuntu-security/cve/2015/CVE-2015-3196.html
  - http://people.canonical.com/~ubuntu-security/cve/2015/CVE-2015-1794.html

**Comment by tianon** [comment]
@andyshinn http://bugs.alpinelinux.org/issues/4921 looks like it's been updated there; can we get an updated `alpine` image with newer `openssl`? :+1:

**Comment by tianon** [comment]
@maxamillion `openssl-1.0.2e-1.fc23 has been pushed to the Fedora 23 stable repository. If problems still persist, please make note of it in this bug report.` seems promising -- `fedora` image update forthcoming? :smile:

**Comment by tianon** [comment]
@flavio it looks like there's been some good activity on those CVE bugs for `opensuse`, but I'm not sure whether what's there means updated/fixed packages are available yet or not; can you help interpret and take the torch from here?

**Comment by tianon** [comment]
@therealprologic looks like `crux` has an updated `openssl/Pkgfile` now (https://crux.nu/gitweb/?p=ports/core.git;a=commit;h=cebb07c1929502695985eafe10b9299f6a2f1179); can we get an updated image? :smile:

**Comment by prologic** [comment]
@tianon Yes of course; in a few days :) (*hopefully this weekend*).

**Comment by tianon** [comment]
@prologic :metal: thanks!

**Comment by tianon** [comment]
@vaygr looks like sourcemage hasn't been updated yet (http://www.sourcemage.org/projects/grimoire/repository/changes/crypto/openssl?rev=master); am I looking in the right places for this kind of information?

**Comment by tianon** [comment]
@juanluisbaptiste `mageia` update appears to be available now! (https://bugs.mageia.org/show_bug.cgi?id=17292)  can we get an updated image? :smile:

**Comment by juanluisbaptiste** [comment]
Done, PR: https://github.com/juanluisbaptiste/docker-brew-mageia/pull/1

I'm sorry for the delay !

**Comment by tianon** [comment]
@Djelibeybi looks like Oracle's updated now also -- can we get some fresh images? :pray: :smile:

**Comment by Djelibeybi** [comment]
I've asked our build team to trigger a rebuild. We will only update oraclelinux:latest, though.

**Comment by Djelibeybi** [comment]
Question for @tianon and others: what makes you trigger one of these CVE rebuilds? The CVEs are moderate/low and usually we wouldn't rebuild unless they were High/Critical. I'm just trying to work out what level to set our automation at, because we wouldn't have considered a rebuild/republish for these CVEs.

**Comment by tianon** [comment]
We have a very low threshold for what we consider important enough to
rebuild the base for because the officially recommended way you fix your
own images in light of a vulnerability is to update the base and rebuild
your image from a Dockerfile; if the base doesn't get updated, the
Dockerfile re-build will be cached (and if the package that needs to be
updated is included in the base image, it wouldn't get updated even if the
build wasn't cached).

We do try to use the CVSS / determined Docker-use-case impact to determine
how actively we should start harassing upstreams, but I try to be
reasonable and not harass you guys until your relevant distribution
actually does have updated packages available.

**Comment by Djelibeybi** [comment]
@tianon fixed in PR #1287.

Also, if you open this sort of issue in future, please ping me earlier. I don't monitor the entire repo. :)

**Comment by vaygr** [comment]
@tianon thanks for the notice, the better place is plain git web-interface here: http://scmweb.sourcemage.org/. We will generate new image shortly and create a new PR for it.

**Comment by tianon** [comment]
@Djelibeybi will do, thanks!

@vaygr ahhh nice, yeah that looks much better :+1:  Thanks! :smile:

**Comment by tianon** [comment]
I think it's probably about time we declared this one "as fixed as it's going to be", and I'm thus going to close this tracking issue.  Thanks folks!

For any maintainers still straggling here, you should definitely focus your efforts on https://github.com/docker-library/official-images/issues/1448 ASAP and consider this openssl update to be a side benefit to fixing that one. :+1:
