### ISSUE TITLE
glibc: CVE-2015-7547

### ISSUE THREAD

**Issue by tianon** [docker-library/official-images#1448]
# CVE-2015-7547: glibc getaddrinfo stack-based buffer overflow

https://googleonlinesecurity.blogspot.no/2016/02/cve-2015-7547-glibc-getaddrinfo-stack.html

---

- [x] `alpine`: no glibc package available
- [x] `busybox`: https://github.com/docker-library/official-images/pull/1451
- [x] `centos` (RHEL derivative): https://github.com/docker-library/official-images/pull/1455
  - https://access.redhat.com/security/cve/CVE-2015-7547
- [ ] `crux`:
  - https://crux.nu/gitweb/?p=ports/core.git;a=history;f=glibc;hb=HEAD
- [x] `debian`: https://github.com/docker-library/official-images/issues/1450
  - https://security-tracker.debian.org/tracker/CVE-2015-7547
- [x] `fedora`: https://github.com/docker-library/official-images/pull/1456, https://github.com/docker-library/official-images/pull/1461
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2015-7547
- [x] `mageia`: https://github.com/docker-library/official-images/pull/1468
  - https://advisories.mageia.org/MGASA-2016-0079.html (https://lwn.net/Articles/676456/)
  - https://bugs.mageia.org/show_bug.cgi?id=17394
  - https://bugs.mageia.org/buglist.cgi?quicksearch=ALL%20CVE-2015-7547
- [x] `opensuse`: https://github.com/docker-library/official-images/pull/1460, https://github.com/docker-library/official-images/pull/1465
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2015-7547
- [x] `oraclelinux`: https://github.com/docker-library/official-images/pull/1453
  - http://linux.oracle.com/cve/CVE-2015-7547.html
- [ ] `photon`:
  - https://github.com/vmware/photon/commit/fdf30faebdb4d1c253e5abbe39f1839536f1e5c0
  - https://github.com/vmware/photon/tree/master/SPECS/glibc
- [ ] `sourcemage`:
  - http://scmweb.sourcemage.org/?p=smgl/grimoire.git;a=history;f=libs/glibc
  - http://www.sourcemage.org/projects/grimoire/search?q=CVE-2015-7547
- [x] `ubuntu`: https://github.com/docker-library/official-images/pull/1454
  - http://people.canonical.com/~ubuntu-security/cve/2015/CVE-2015-7547.html
    - http://people.canonical.com/~ubuntu-security/cve/priority.html (for reference)
  - http://www.ubuntu.com/usn/usn-2900-1/

**Comment by tianon** [comment]
RHEL 6 and RHEL 7 have fixes (cc @jperrin)

Fedora has an update submitted (cc @maxamillion)

openSUSE update is in-progress (cc @flavio)

**Comment by tianon** [comment]
Debian tarballs are in-progress

Ubuntu doesn't have updated packages yet

**Comment by jperrin** [comment]
our packages are syncing to the mirrors now. I'll have an updated build shortly.

**Comment by Djelibeybi** [comment]
OL6 and OL7 have fixes and a new build has been requested from our build team.

**Comment by ThiefMaster** [comment]
will all the official docker-library images be rebuilt automatically?

**Comment by tianon** [comment]
@ThiefMaster yes, they're in-progress right now

@jperrin @Djelibeybi thanks for the updates! :+1:

**Comment by diogomonica** [comment]
@tianon http://www.ubuntu.com/usn/usn-2900-1/

**Comment by tianon** [comment]
@diogomonica nice -- wonder why they didn't update http://people.canonical.com/~ubuntu-security/cve/2015/CVE-2015-7547.html yet

I'll give our Canonical contacts a poke and see what the ETA for updated tarballs is.

**Comment by diogomonica** [comment]
@tianon yeah, I didn't understand that either. I was checking the CVE page too.

**Comment by tianon** [comment]
Heard back and Ubuntu rebuilds are in progress downstream! :+1:

**Comment by diogomonica** [comment]
Great!

![patch all the things](https://static.spiceworks.com/shared/post/0003/6714/patch_all_the_things.jpg)

**Comment by tianon** [comment]
As a minor update, there was a snag in Canonical's update process that's delayed the artifact generation on their side -- I'll keep an eye on things, but it looks like we likely won't get those artifacts until early tomorrow (relative to PST).

**Comment by Djelibeybi** [comment]
Oracle images updated in #1453

**Comment by ThiefMaster** [comment]
What's the best way to see whether an official image has already been updated or not?

**Comment by macropin** [comment]
@tianon when can we expect all the major images to be rebuilt eg `centos` and secondary eg `mariadb`, `nginx` etc? It looks like you guys have gone to bed. We are sitting around waiting for this to happen so we can patch production systems. Thanks.

**Comment by tianon** [comment]
@macropin for CentOS, we're waiting for the image maintainer to provide an updated rootfs; for the Debian-based portion of the library, we're waiting for the images themselves to finish rebuilding

Ubuntu is going to have a PR shortly.

**Comment by tianon** [comment]
Both `ubuntu` and `buildpack-deps` are now fully updated.  Rebuilds of dependent images are still in-progress.

**Comment by flavio** [comment]
Just a quick update, openSUSE 42.1, 13.2 and tumbleweed packages are being rolled out at different paces. I'll update all the images as soon as the packages are there.

**Comment by ThiefMaster** [comment]
Out of curiosity, why do the rebuilds take so long for the debian-based images?

**Comment by tianon** [comment]
That'd mostly be because we have over 300 officially supported tags based directly on `debian`, and over 200 based indirectly on it via `buildpack-deps` (not to mention further chains going through language images).

**Comment by tianon** [comment]
Thanks @flavio! :heart:

**Comment by jperrin** [comment]
Sorry for the delay on getting this one in. https://github.com/docker-library/official-images/pull/1455

**Comment by maxamillion** [comment]
Fedora updated https://github.com/docker-library/official-images/pull/1456

**Comment by tianon** [comment]
@jperrin @maxamillion thanks for your diligence :+1:

Updating on the rebuild status, we're still rebuilding, but I've started pushing batches of images (especially those based directly on the updated base images, which should include most of the "service" images like `nginx` or `mariadb`).

**Comment by tianon** [comment]
@prologic @vaygr looks like `crux` and `sourcemage` are updated now :smile:

**Comment by prologic** [comment]
Awesome :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by tianon** [comment]
So an updated image is coming soon? :wink:

**Comment by macropin** [comment]
`fedora:22` image is still not updated. Tried pulling from two locations (AU and SG) both got `Digest: sha256:6acac77cc134c673eda753de389551d10e7b8d014430bb562bcfd104b6123ee8` which is 3 months old.

**Comment by tianon** [comment]
@maxamillion is the update for `fedora:22` still pending (either in the package repos, or in rootfs rebuilding), or is that going to be a WONTFIX?

**Comment by tianon** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1308943#c7 claims the update is available :smile:

**Comment by macropin** [comment]
And the latest `fedora:23` image contains the vulnerable glibc. 

```
[root@docker docker-cve]# docker pull fedora:23 
Trying to pull repository docker.io/library/fedora ... 23: Pulling from library/fedora
b0082ba983ef: Already exists 
a7a02e6029ae: Already exists 
Digest: sha256:f538e5517cb2160e869647f0bff049e4ee38d5dde4ba75b50ff213831426ba05
Status: Image is up to date for docker.io/fedora:23
[root@docker docker-cve]# docker images |grep fedora
docker.io/fedora                     23                  a7a02e6029ae        8 hours ago         204.4 MB
docker.io/fedora                     latest              a7a02e6029ae        8 hours ago         204.4 MB
[root@docker docker-cve]# docker run --rm -ti fedora:23 bash
[root@db80f371f2e1 /]# rpm -qva |grep glibc
glibc-common-2.22-7.fc23.x86_64
glibc-2.22-7.fc23.x86_64
```

**Comment by tianon** [comment]
@macropin thanks for the additional info and testing -- @maxamillion thoughts on what might've happened? :confused:

**Comment by tianon** [comment]
@frapposelli just realized I need to add `photon` to my template :smile:  Is there an official "security tracker" for the OS yet, or is the best place to look for updates just going to be the `SPECS` directory in https://github.com/vmware/photon ?  It doesn't look like `glibc` there is updated yet (https://github.com/vmware/photon/tree/master/SPECS/glibc).

**Comment by maxamillion** [comment]
@macropin @tianon - yup, totally my fault. I'm getting that fixed up and the Fedora 22 image built, will have a pull request asap. Apologies.

**Comment by frapposelli** [comment]
@tianon no security tracker at the moment (working on that), best way is to look at the SPEC dir (either `master` or `dev` branch).

Seems like the guys already pushed a patch: vmware/photon@fdf30faebdb4d1c253e5abbe39f1839536f1e5c0

**Comment by maxamillion** [comment]
@tianon Apologies for the mistake and the delay on the F22 image. https://github.com/docker-library/official-images/pull/1461

**Comment by tianon** [comment]
Ok, Fedora fix is pushed. :smile: :+1:

**Comment by tianon** [comment]
@frapposelli nice! :smile:  Does that mean it's ready for an image rootfs rebuild, or is there further process it has to go through first?

**Comment by frapposelli** [comment]
@tianon they have an automated process that uploads the new artifacts, I'm checking with them for a timeline, once they're up I will send a PR with the update :+1:

**Comment by tianon** [comment]
@frapposelli rock on, sounds great :heart:

**Comment by tianon** [comment]
@juanluisbaptiste looks like `mageia:5` is ready for a rootfs rebuild? :smile:

- https://advisories.mageia.org/MGASA-2016-0079.html (https://lwn.net/Articles/676456/)
- https://bugs.mageia.org/show_bug.cgi?id=17394

**Comment by juanluisbaptiste** [comment]
@tianon yes I already did the image update locally, but it  seems I got distracted by something and totally forgot to finish it, probably I saw a squirrel through the window or something hehe.  I'll finish the update later today when I'm back home.

**Comment by juanluisbaptiste** [comment]
@tianon Ready, please check.

**Comment by tianon** [comment]
I think this is likely as good as it's going to get at this point. :+1:
