### ISSUE TITLE
openssl: CVE-2016-0800, CVE-2016-0705, CVE-2016-0798, CVE-2016-0797, CVE-2016-0702, CVE-2016-0703, CVE-2016-0799, CVE-2016-0704

### ISSUE THREAD

**Issue by tianon** [docker-library/official-images#1490]
# CVE-2016-0800 ("DROWN"), CVE-2016-0799, CVE-2016-0798, CVE-2016-0797, CVE-2016-0705, CVE-2016-0704, CVE-2016-0703, CVE-2016-0702 ("Cache Bleed")

https://mta.openssl.org/pipermail/openssl-announce/2016-March/000066.html

- https://www.openssl.org/news/vulnerabilities.html#2016-0800
  - https://drownattack.com
  - Fixed in OpenSSL **1.0.1s** (Affected 1.0.1r, 1.0.1q, 1.0.1p, 1.0.1o, 1.0.1n, 1.0.1m, 1.0.1l, 1.0.1k, 1.0.1j, 1.0.1i, 1.0.1h, 1.0.1g, 1.0.1f, 1.0.1e, 1.0.1d, 1.0.1c, 1.0.1b, 1.0.1a, 1.0.1)
  - Fixed in OpenSSL **1.0.2g** (Affected 1.0.2f, 1.0.2e, 1.0.2d, 1.0.2c, 1.0.2b, 1.0.2a, 1.0.2)
- https://www.openssl.org/news/vulnerabilities.html#2016-0799
  - https://guidovranken.wordpress.com/2016/02/27/openssl-cve-2016-0799-heap-corruption-via-bio_printf/
  - Fixed in OpenSSL **1.0.1s** (Affected 1.0.1r, 1.0.1q, 1.0.1p, 1.0.1o, 1.0.1n, 1.0.1m, 1.0.1l, 1.0.1k, 1.0.1j, 1.0.1i, 1.0.1h, 1.0.1g, 1.0.1f, 1.0.1e, 1.0.1d, 1.0.1c, 1.0.1b, 1.0.1a, 1.0.1)
  - Fixed in OpenSSL **1.0.2g** (Affected 1.0.2f, 1.0.2e, 1.0.2d, 1.0.2c, 1.0.2b, 1.0.2a, 1.0.2)
- https://www.openssl.org/news/vulnerabilities.html#2016-0798
  - Fixed in OpenSSL **1.0.1s** (Affected 1.0.1r, 1.0.1q, 1.0.1p, 1.0.1o, 1.0.1n, 1.0.1m, 1.0.1l, 1.0.1k, 1.0.1j, 1.0.1i, 1.0.1h, 1.0.1g, 1.0.1f, 1.0.1e, 1.0.1d, 1.0.1c, 1.0.1b, 1.0.1a, 1.0.1)
  - Fixed in OpenSSL **1.0.2g** (Affected 1.0.2f, 1.0.2e, 1.0.2d, 1.0.2c, 1.0.2b, 1.0.2a, 1.0.2)
- https://www.openssl.org/news/vulnerabilities.html#2016-0797
  - Fixed in OpenSSL **1.0.1s** (Affected 1.0.1r, 1.0.1q, 1.0.1p, 1.0.1o, 1.0.1n, 1.0.1m, 1.0.1l, 1.0.1k, 1.0.1j, 1.0.1i, 1.0.1h, 1.0.1g, 1.0.1f, 1.0.1e, 1.0.1d, 1.0.1c, 1.0.1b, 1.0.1a, 1.0.1)
  - Fixed in OpenSSL **1.0.2g** (Affected 1.0.2f, 1.0.2e, 1.0.2d, 1.0.2c, 1.0.2b, 1.0.2a, 1.0.2)
- https://www.openssl.org/news/vulnerabilities.html#2016-0705
  - Fixed in OpenSSL **1.0.1s** (Affected 1.0.1r, 1.0.1q, 1.0.1p, 1.0.1o, 1.0.1n, 1.0.1m, 1.0.1l, 1.0.1k, 1.0.1j, 1.0.1i, 1.0.1h, 1.0.1g, 1.0.1f, 1.0.1e, 1.0.1d, 1.0.1c, 1.0.1b, 1.0.1a, 1.0.1)
  - Fixed in OpenSSL **1.0.2g** (Affected 1.0.2f, 1.0.2e, 1.0.2d, 1.0.2c, 1.0.2b, 1.0.2a, 1.0.2)
- https://www.openssl.org/news/vulnerabilities.html#2016-0704
  - Fixed in OpenSSL **0.9.8zf** (Affected 0.9.8ze, 0.9.8zd, 0.9.8zc, 0.9.8zb, 0.9.8za, 0.9.8y, 0.9.8x, 0.9.8w, 0.9.8v, 0.9.8u, 0.9.8t, 0.9.8s, 0.9.8r, 0.9.8q, 0.9.8p, 0.9.8o, 0.9.8n, 0.9.8m, 0.9.8l, 0.9.8k, 0.9.8j, 0.9.8i, 0.9.8h, 0.9.8g, 0.9.8f, 0.9.8e, 0.9.8d, 0.9.8c, 0.9.8b, 0.9.8a, 0.9.8)
  - Fixed in OpenSSL **1.0.0r** (Affected 1.0.0q, 1.0.0p, 1.0.0o, 1.0.0n, 1.0.0m, 1.0.0l, 1.0.0k, 1.0.0j, 1.0.0i, 1.0.0g, 1.0.0f, 1.0.0e, 1.0.0d, 1.0.0c, 1.0.0b, 1.0.0a, 1.0.0)
  - Fixed in OpenSSL **1.0.1m** (Affected 1.0.1l, 1.0.1k, 1.0.1j, 1.0.1i, 1.0.1h, 1.0.1g, 1.0.1f, 1.0.1e, 1.0.1d, 1.0.1c, 1.0.1b, 1.0.1a, 1.0.1)
  - Fixed in OpenSSL **1.0.2a** (Affected 1.0.2)
- https://www.openssl.org/news/vulnerabilities.html#2016-0703
  - Fixed in OpenSSL **0.9.8zf** (Affected 0.9.8ze, 0.9.8zd, 0.9.8zc, 0.9.8zb, 0.9.8za, 0.9.8y, 0.9.8x, 0.9.8w, 0.9.8v, 0.9.8u, 0.9.8t, 0.9.8s, 0.9.8r, 0.9.8q, 0.9.8p, 0.9.8o, 0.9.8n, 0.9.8m, 0.9.8l, 0.9.8k, 0.9.8j, 0.9.8i, 0.9.8h, 0.9.8g, 0.9.8f, 0.9.8e, 0.9.8d, 0.9.8c, 0.9.8b, 0.9.8a, 0.9.8)
  - Fixed in OpenSSL **1.0.0r** (Affected 1.0.0q, 1.0.0p, 1.0.0o, 1.0.0n, 1.0.0m, 1.0.0l, 1.0.0k, 1.0.0j, 1.0.0i, 1.0.0g, 1.0.0f, 1.0.0e, 1.0.0d, 1.0.0c, 1.0.0b, 1.0.0a, 1.0.0)
  - Fixed in OpenSSL **1.0.1m** (Affected 1.0.1l, 1.0.1k, 1.0.1j, 1.0.1i, 1.0.1h, 1.0.1g, 1.0.1f, 1.0.1e, 1.0.1d, 1.0.1c, 1.0.1b, 1.0.1a, 1.0.1)
  - Fixed in OpenSSL **1.0.2a** (Affected 1.0.2)
- https://www.openssl.org/news/vulnerabilities.html#2016-0702
  - https://cachebleed.info
  - Fixed in OpenSSL **1.0.1s** (Affected 1.0.1r, 1.0.1q, 1.0.1p, 1.0.1o, 1.0.1n, 1.0.1m, 1.0.1l, 1.0.1k, 1.0.1j, 1.0.1i, 1.0.1h, 1.0.1g, 1.0.1f, 1.0.1e, 1.0.1d, 1.0.1c, 1.0.1b, 1.0.1a, 1.0.1)
  - Fixed in OpenSSL **1.0.2g** (Affected 1.0.2f, 1.0.2e, 1.0.2d, 1.0.2c, 1.0.2b, 1.0.2a, 1.0.2)

---

- [x] `alpine`: https://github.com/docker-library/official-images/issues/1496
  - http://git.alpinelinux.org/cgit/aports/log/main/openssl?h=3.3-stable
  - http://git.alpinelinux.org/cgit/aports/log/main/openssl?h=3.2-stable
  - http://git.alpinelinux.org/cgit/aports/log/main/openssl?h=3.1-stable
  - http://git.alpinelinux.org/cgit/aports/log/main/openssl
  - http://bugs.alpinelinux.org/projects/alpine/search?q=CVE-2016-0800
  - http://bugs.alpinelinux.org/projects/alpine/search?q=CVE-2016-0799
  - http://bugs.alpinelinux.org/projects/alpine/search?q=CVE-2016-0798
  - http://bugs.alpinelinux.org/projects/alpine/search?q=CVE-2016-0797
  - http://bugs.alpinelinux.org/projects/alpine/search?q=CVE-2016-0705
  - http://bugs.alpinelinux.org/projects/alpine/search?q=CVE-2016-0704
  - http://bugs.alpinelinux.org/projects/alpine/search?q=CVE-2016-0703
  - http://bugs.alpinelinux.org/projects/alpine/search?q=CVE-2016-0702
- [x] `busybox`: *not applicable*
- [x] `centos` (RHEL derivative): https://github.com/docker-library/official-images/pull/1513
  - https://access.redhat.com/security/cve/CVE-2016-0800
  - https://access.redhat.com/security/cve/CVE-2016-0799
  - ~~https://access.redhat.com/security/cve/CVE-2016-0798~~
  - https://access.redhat.com/security/cve/CVE-2016-0797
  - https://access.redhat.com/security/cve/CVE-2016-0705
  - ~~https://access.redhat.com/security/cve/CVE-2016-0704~~
  - ~~https://access.redhat.com/security/cve/CVE-2016-0703~~
  - https://access.redhat.com/security/cve/CVE-2016-0702
- [ ] `crux`: ???
  - https://crux.nu/gitweb/?p=ports/core.git;a=history;f=openssl;hb=HEAD
- [x] `debian`: https://github.com/docker-library/official-images/pull/1495
  - ~~https://security-tracker.debian.org/tracker/CVE-2016-0800~~
  - https://security-tracker.debian.org/tracker/CVE-2016-0799
  - https://security-tracker.debian.org/tracker/CVE-2016-0798
  - https://security-tracker.debian.org/tracker/CVE-2016-0797
  - https://security-tracker.debian.org/tracker/CVE-2016-0705
  - ~~https://security-tracker.debian.org/tracker/CVE-2016-0704~~
  - ~~https://security-tracker.debian.org/tracker/CVE-2016-0703~~
  - https://security-tracker.debian.org/tracker/CVE-2016-0702
- [x] `fedora`: https://github.com/docker-library/official-images/pull/1517
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-0800
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-0799
  - ~~https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-0798~~
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-0797
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-0705
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-0704
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-0703
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-0702
- [x] `mageia`: https://github.com/docker-library/official-images/pull/1514
  - https://bugs.mageia.org/show_bug.cgi?id=17859
- [x] `opensuse`: https://github.com/docker-library/official-images/pull/1501
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2016-0800
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2016-0799
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2016-0798
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2016-0797
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2016-0705
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2016-0704
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2016-0703
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2016-0702
- [x] `oraclelinux`: https://github.com/docker-library/official-images/pull/1508
  - http://linux.oracle.com/cve/CVE-2016-0800.html
  - http://linux.oracle.com/cve/CVE-2016-0799.html
  - http://linux.oracle.com/cve/CVE-2016-0798.html
  - http://linux.oracle.com/cve/CVE-2016-0797.html
  - http://linux.oracle.com/cve/CVE-2016-0705.html
  - http://linux.oracle.com/cve/CVE-2016-0704.html
  - http://linux.oracle.com/cve/CVE-2016-0703.html
  - http://linux.oracle.com/cve/CVE-2016-0702.html
- [ ] `photon`:
  - https://github.com/vmware/photon/tree/master/SPECS/openssl
  - https://github.com/vmware/photon/tree/dev/SPECS/openssl
- [ ] `sourcemage`:
  - http://scmweb.sourcemage.org/?p=smgl/grimoire.git;a=history;f=crypto/openssl
  - http://www.sourcemage.org/projects/grimoire/search?q=CVE-2016-0800
  - http://www.sourcemage.org/projects/grimoire/search?q=CVE-2016-0799
  - http://www.sourcemage.org/projects/grimoire/search?q=CVE-2016-0798
  - http://www.sourcemage.org/projects/grimoire/search?q=CVE-2016-0797
  - http://www.sourcemage.org/projects/grimoire/search?q=CVE-2016-0705
  - http://www.sourcemage.org/projects/grimoire/search?q=CVE-2016-0704
  - http://www.sourcemage.org/projects/grimoire/search?q=CVE-2016-0703
  - http://www.sourcemage.org/projects/grimoire/search?q=CVE-2016-0702
- [x] `ubuntu`: https://github.com/docker-library/official-images/pull/1509
  - ~~http://people.canonical.com/~ubuntu-security/cve/2016/CVE-2016-0800.html~~
  - http://people.canonical.com/~ubuntu-security/cve/2016/CVE-2016-0799.html
  - http://people.canonical.com/~ubuntu-security/cve/2016/CVE-2016-0798.html
  - http://people.canonical.com/~ubuntu-security/cve/2016/CVE-2016-0797.html
  - http://people.canonical.com/~ubuntu-security/cve/2016/CVE-2016-0705.html
  - ~~http://people.canonical.com/~ubuntu-security/cve/2016/CVE-2016-0704.html~~
  - ~~http://people.canonical.com/~ubuntu-security/cve/2016/CVE-2016-0703.html~~
  - http://people.canonical.com/~ubuntu-security/cve/2016/CVE-2016-0702.html
    - http://people.canonical.com/~ubuntu-security/cve/priority.html (for reference)
  - https://partner-images.canonical.com/core/

**Comment by tianon** [comment]
Just to reiterate -- the fix is _not_ released yet, and [not scheduled to be released until tomorrow](https://mta.openssl.org/pipermail/openssl-announce/2016-February/000063.html) (although the fix [is committed in upstream's Git repo](https://github.com/openssl/openssl/commit/9cb177301fdab492e4cfef376b28339afe3ef663)), but the vulnerability is now public so I'm jumping straight into a tracker issue so we can keep tabs on our status as this develops.

**Comment by tianon** [comment]
@andyshinn looks like Alpine is ready :smile:

@prologic Crux appears to be ready

@maxamillion `openssl-1.0.2g-1.fc23 has been submitted as an update to Fedora 23.`

@flavio https://bugzilla.novell.com/show_bug.cgi?id=CVE-2016-0800 am I reading correctly that updates are available here?

@Djelibeybi Oracle Linux has the fix available now, correct? (am I reading the status pages correctly there?)

@vaygr looks like SourceMage has the update available too :+1:

**Comment by Djelibeybi** [comment]
Yes, we pushed the RPMs out just over an hour ago. Our Docker images have been built and are currently in QA for sanity and regression testing.

**Comment by tianon** [comment]
@jperrin am I reading correctly that CentOS should be fixed for all except CVE-2016-0799 now?

**Comment by tianon** [comment]
@juanluisbaptiste looks like Mageia is fixed and ready for a rebuild now :smile:

**Comment by tianon** [comment]
@frapposelli any idea what's up with Photon WRT this vuln? :smile:

**Comment by jperrin** [comment]
@tianon updates are in https://github.com/docker-library/official-images/pull/1513

**Comment by juanluisbaptiste** [comment]
@tianon working on it...

**Comment by juanluisbaptiste** [comment]
@tianon done, please check my PR.

**Comment by maxamillion** [comment]
@tianon Fedora updated here: https://github.com/docker-library/official-images/pull/1517

**Comment by tianon** [comment]
I think this is likely as good as it's going to get at this point. :+1:
