### ISSUE TITLE
git: CVE-2016-2324 CVE-2016-2315

### ISSUE THREAD

**Issue by yosifkit** [docker-library/official-images#1561]
# CVE-2016-2324 CVE-2016-2315

CVE-2016-2315, CVE-2016-2324: https://bugzilla.redhat.com/show_bug.cgi?id=1317981#c30
  - Fixed in `git` 2.4.11, 2.5.5, 2.6.6, and 2.7.4 (https://marc.info/?l=git&m=145824889421350)

---

- [x] `docker:git` (`FROM alpine:3.3`):
  - http://git.alpinelinux.org/cgit/aports/log/main/git?h=3.3-stable
- [x] `buildpack-deps:scm` (`debian`):
  - https://security-tracker.debian.org/tracker/CVE-2016-2324
  - https://security-tracker.debian.org/tracker/CVE-2016-2315
- [x] `buildpack-deps:scm` (`ubuntu`):
  - http://people.ubuntu.com/~ubuntu-security/cve/CVE-2016-2324
  - http://people.ubuntu.com/~ubuntu-security/cve/CVE-2016-2315
    - http://people.canonical.com/~ubuntu-security/cve/priority.html (for reference)
  - https://partner-images.canonical.com/core/
- [x] `ros:*core` (`ubuntu:trusty`)

**Comment by yosifkit** [comment]
Since all the fixes have landed upstream, it should just be a force rebuild on buildpacks, docker and ros.  Which is starting on the build server shortly.

**Comment by yosifkit** [comment]
Woot, `buildpack-deps`, `docker:git` and `ros` are pushed.  All of the dependent images are still building and will probably push in the morning pacific time.
```console
$ docker pull buildpack-deps
Using default tag: latest
latest: Pulling from library/buildpack-deps

678df6831d0b: Pull complete 
df827ef7cf3b: Pull complete 
Digest: sha256:e01834ff5b9d23a8199ebf728bc79945afa06a5753b4f2537c62df25ce38dddb
Status: Downloaded newer image for buildpack-deps:latest
$ docker run -it --rm buildpack-deps
root@ff48e36945d7:/# apt-cache show git | grep Version
Version: 1:2.1.4-2.1+deb8u2

$ docker pull docker:git
git: Pulling from library/docker
aea2945377ae: Pull complete 
Digest: sha256:599743a349987ab1d3e45b0ce190b24b11f11d750685cc6b0a03c17a70f68ad2
Status: Downloaded newer image for docker:git
$ docker run -it --rm docker:git
/ # git --version
git version 2.6.6

$ docker run -it --rm ros:indigo-ros-core
root@8bd9f7ad448b:/# apt-cache show git | grep Version
Version: 1:1.9.1-1ubuntu0.3
root@8bd9f7ad448b:/# 
```

**Comment by yosifkit** [comment]
Everything has been pushed! (aside from jdk 9 since we can't build it with https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816440)
