### ISSUE TITLE
openssl: CVE-2016-2105, CVE-2016-2106, CVE-2016-2107, CVE-2016-2108, CVE-2016-2109, CVE-2016-2176

### ISSUE THREAD

**Issue by tianon** [docker-library/official-images#1691]
# CVE-2016-2105, CVE-2016-2106, CVE-2016-2107, CVE-2016-2108, CVE-2016-2109, CVE-2016-2176

https://mta.openssl.org/pipermail/openssl-announce/2016-May/000072.html

CVE-2016-2105: https://www.openssl.org/news/vulnerabilities.html#2016-2105
  - Fixed in OpenSSL 1.0.1t (Affected 1.0.1s, 1.0.1r, 1.0.1q, 1.0.1p, 1.0.1o, 1.0.1n, 1.0.1m, 1.0.1l, 1.0.1k, 1.0.1j, 1.0.1i, 1.0.1h, 1.0.1g, 1.0.1f, 1.0.1e, 1.0.1d, 1.0.1c, 1.0.1b, 1.0.1a, 1.0.1)
  - Fixed in OpenSSL 1.0.2h (Affected 1.0.2g, 1.0.2f, 1.0.2e, 1.0.2d, 1.0.2c, 1.0.2b, 1.0.2a, 1.0.2)

CVE-2016-2106: https://www.openssl.org/news/vulnerabilities.html#2016-2106
  - Fixed in OpenSSL 1.0.1t (Affected 1.0.1s, 1.0.1r, 1.0.1q, 1.0.1p, 1.0.1o, 1.0.1n, 1.0.1m, 1.0.1l, 1.0.1k, 1.0.1j, 1.0.1i, 1.0.1h, 1.0.1g, 1.0.1f, 1.0.1e, 1.0.1d, 1.0.1c, 1.0.1b, 1.0.1a, 1.0.1)
  - Fixed in OpenSSL 1.0.2h (Affected 1.0.2g, 1.0.2f, 1.0.2e, 1.0.2d, 1.0.2c, 1.0.2b, 1.0.2a, 1.0.2)

CVE-2016-2107: https://www.openssl.org/news/vulnerabilities.html#2016-2107
  - Fixed in OpenSSL 1.0.1t (Affected 1.0.1s, 1.0.1r, 1.0.1q, 1.0.1p, 1.0.1o, 1.0.1n, 1.0.1m, 1.0.1l, 1.0.1k, 1.0.1j, 1.0.1i, 1.0.1h, 1.0.1g, 1.0.1f, 1.0.1e, 1.0.1d, 1.0.1c, 1.0.1b, 1.0.1a, 1.0.1)
  - Fixed in OpenSSL 1.0.2h (Affected 1.0.2g, 1.0.2f, 1.0.2e, 1.0.2d, 1.0.2c, 1.0.2b, 1.0.2a, 1.0.2)

CVE-2016-2108: https://www.openssl.org/news/vulnerabilities.html#2016-2108
  - Fixed in OpenSSL 1.0.1o (Affected 1.0.1n, 1.0.1m, 1.0.1l, 1.0.1k, 1.0.1j, 1.0.1i, 1.0.1h, 1.0.1g, 1.0.1f, 1.0.1e, 1.0.1d, 1.0.1c, 1.0.1b, 1.0.1a, 1.0.1)
  - Fixed in OpenSSL 1.0.2c (Affected 1.0.2b, 1.0.2a, 1.0.2)

CVE-2016-2109: https://www.openssl.org/news/vulnerabilities.html#2016-2109
  - Fixed in OpenSSL 1.0.1t (Affected 1.0.1s, 1.0.1r, 1.0.1q, 1.0.1p, 1.0.1o, 1.0.1n, 1.0.1m, 1.0.1l, 1.0.1k, 1.0.1j, 1.0.1i, 1.0.1h, 1.0.1g, 1.0.1f, 1.0.1e, 1.0.1d, 1.0.1c, 1.0.1b, 1.0.1a, 1.0.1)
  - Fixed in OpenSSL 1.0.2h (Affected 1.0.2g, 1.0.2f, 1.0.2e, 1.0.2d, 1.0.2c, 1.0.2b, 1.0.2a, 1.0.2)

CVE-2016-2176: https://www.openssl.org/news/vulnerabilities.html#2016-2176
  - Fixed in OpenSSL 1.0.1t (Affected 1.0.1s, 1.0.1r, 1.0.1q, 1.0.1p, 1.0.1o, 1.0.1n, 1.0.1m, 1.0.1l, 1.0.1k, 1.0.1j, 1.0.1i, 1.0.1h, 1.0.1g, 1.0.1f, 1.0.1e, 1.0.1d, 1.0.1c, 1.0.1b, 1.0.1a, 1.0.1)
  - Fixed in OpenSSL 1.0.2h (Affected 1.0.2g, 1.0.2f, 1.0.2e, 1.0.2d, 1.0.2c, 1.0.2b, 1.0.2a, 1.0.2)

---

- [x] `alpine`: https://github.com/docker-library/official-images/pull/1708
  - `edge`: http://git.alpinelinux.org/cgit/aports/commit/?id=cbb0770
  - http://git.alpinelinux.org/cgit/aports/log/main/openssl?h=3.3-stable
  - http://git.alpinelinux.org/cgit/aports/log/main/openssl?h=3.2-stable
  - http://git.alpinelinux.org/cgit/aports/log/main/openssl?h=3.1-stable
  - http://git.alpinelinux.org/cgit/aports/log/main/openssl
  - http://bugs.alpinelinux.org/projects/alpine/search?q=CVE-2016-2105
  - http://bugs.alpinelinux.org/projects/alpine/search?q=CVE-2016-2106
  - http://bugs.alpinelinux.org/projects/alpine/search?q=CVE-2016-2107
  - http://bugs.alpinelinux.org/projects/alpine/search?q=CVE-2016-2108
  - http://bugs.alpinelinux.org/projects/alpine/search?q=CVE-2016-2109
  - http://bugs.alpinelinux.org/projects/alpine/search?q=CVE-2016-2176
- [x] ~~`busybox`~~
- [x] `centos` (RHEL derivative): https://github.com/docker-library/official-images/pull/1744, https://github.com/docker-library/official-images/pull/1746
  - https://access.redhat.com/security/cve/CVE-2016-2105
  - https://access.redhat.com/security/cve/CVE-2016-2106
  - https://access.redhat.com/security/cve/CVE-2016-2107
  - https://access.redhat.com/security/cve/CVE-2016-2108
  - https://access.redhat.com/security/cve/CVE-2016-2109
  - https://access.redhat.com/security/cve/CVE-2016-2176
- [ ] `crux`:
  - https://crux.nu/gitweb/?p=ports/core.git;a=history;f=openssl;hb=HEAD
- [x] `debian`: https://github.com/docker-library/official-images/pull/1695
  - https://www.debian.org/security/2016/dsa-3566  
    (https://lists.debian.org/debian-security-announce/2016/msg00142.html)
  - https://security-tracker.debian.org/tracker/CVE-2016-2105
  - https://security-tracker.debian.org/tracker/CVE-2016-2106
  - https://security-tracker.debian.org/tracker/CVE-2016-2107
  - ~~https://security-tracker.debian.org/tracker/CVE-2016-2108~~
  - https://security-tracker.debian.org/tracker/CVE-2016-2109
  - https://security-tracker.debian.org/tracker/CVE-2016-2176
- [x] `fedora`: https://github.com/docker-library/official-images/pull/1862
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-2105
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-2106
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-2107
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-2108
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-2109
  - https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-2176
- [ ] `mageia`:
  - https://advisories.mageia.org/CVE-2016-2105.html
  - https://advisories.mageia.org/CVE-2016-2106.html
  - https://advisories.mageia.org/CVE-2016-2107.html
  - https://advisories.mageia.org/CVE-2016-2108.html
  - https://advisories.mageia.org/CVE-2016-2109.html
  - https://advisories.mageia.org/CVE-2016-2176.html
  - https://bugs.mageia.org/buglist.cgi?quicksearch=ALL%20CVE-2016-2105
  - https://bugs.mageia.org/buglist.cgi?quicksearch=ALL%20CVE-2016-2106
  - https://bugs.mageia.org/buglist.cgi?quicksearch=ALL%20CVE-2016-2107
  - https://bugs.mageia.org/buglist.cgi?quicksearch=ALL%20CVE-2016-2108
  - https://bugs.mageia.org/buglist.cgi?quicksearch=ALL%20CVE-2016-2109
  - https://bugs.mageia.org/buglist.cgi?quicksearch=ALL%20CVE-2016-2176
- [ ] `opensuse`:
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2016-2105
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2016-2106
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2016-2107
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2016-2108
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2016-2109
  - https://bugzilla.novell.com/show_bug.cgi?id=CVE-2016-2176
- [x] `oraclelinux`: https://github.com/docker-library/official-images/pull/1722, https://github.com/docker-library/official-images/pull/1732
  - http://linux.oracle.com/cve/CVE-2016-2105.html
  - http://linux.oracle.com/cve/CVE-2016-2106.html
  - http://linux.oracle.com/cve/CVE-2016-2107.html
  - http://linux.oracle.com/cve/CVE-2016-2108.html
  - http://linux.oracle.com/cve/CVE-2016-2109.html
  - http://linux.oracle.com/cve/CVE-2016-2176.html
- [ ] `photon`:
  - https://github.com/vmware/photon/tree/master/SPECS/openssl
  - https://github.com/vmware/photon/tree/dev/SPECS/openssl
- [ ] `sourcemage`:
  - http://scmweb.sourcemage.org/?p=smgl/grimoire.git;a=history;f=crypto/openssl
  - http://www.sourcemage.org/projects/grimoire/search?q=CVE-2016-2105
  - http://www.sourcemage.org/projects/grimoire/search?q=CVE-2016-2106
  - http://www.sourcemage.org/projects/grimoire/search?q=CVE-2016-2107
  - http://www.sourcemage.org/projects/grimoire/search?q=CVE-2016-2108
  - http://www.sourcemage.org/projects/grimoire/search?q=CVE-2016-2109
  - http://www.sourcemage.org/projects/grimoire/search?q=CVE-2016-2176
- [x] `ubuntu`: https://github.com/docker-library/official-images/pull/1696
  - http://www.ubuntu.com/usn/usn-2959-1/
  - http://people.ubuntu.com/~ubuntu-security/cve/CVE-2016-2105
  - http://people.ubuntu.com/~ubuntu-security/cve/CVE-2016-2106
  - http://people.ubuntu.com/~ubuntu-security/cve/CVE-2016-2107
  - http://people.ubuntu.com/~ubuntu-security/cve/CVE-2016-2108
  - http://people.ubuntu.com/~ubuntu-security/cve/CVE-2016-2109
  - ~~http://people.ubuntu.com/~ubuntu-security/cve/CVE-2016-2176~~
    - http://people.canonical.com/~ubuntu-security/cve/priority.html (for reference)
  - https://partner-images.canonical.com/core/

**Comment by Djelibeybi** [comment]
@tianon the PR for this may come from another Oracle engineer, as I will be travelling all day tomorrow. All depends on when the images are built and QA completes. Just flagging this now, so as not to potentially delay the merge process.

**Comment by tianon** [comment]
Sweet, thanks @Djelibeybi!

**Comment by tianon** [comment]
@maxamillion at the very least, it appears Fedora 23 has a bunch of updates available (not sure about other versions) :+1:

**Comment by tianon** [comment]
@jperrin some of those CentOS/RHEL links still say "Affected" -- is there fixes still forthcoming on this one?

**Comment by tianon** [comment]
@andyshinn looks like Alpine has updates available; wanna do a rebuild? :smile:

**Comment by jperrin** [comment]
Yup. I'll have a pull request for you shortly

**Comment by Djelibeybi** [comment]
PR #1722 submitted to update Oracle Linux 7.2.

**Comment by Djelibeybi** [comment]
PR #1732 submitted to update Oracle Linux 6.7.

**Comment by maxamillion** [comment]
@tianon FWIW, Fedora is blocked on https://github.com/docker/docker/issues/20331

**Comment by maxamillion** [comment]
https://github.com/docker-library/official-images/pull/1862

**Comment by Djelibeybi** [comment]
PR #1871 submitted to update Oracle Linux 5.11.

**Comment by tianon** [comment]
I think this is likely as good as it's going to get at this point. :+1:
